version: '3.9'
services:
  yolo-web-db:
    image: mongo:5.0.16
    environment:
      MONGO_DATABASE: yolomy
    ports:
      - 27017:27017
  yolo-web-client:
    image: muriithike/yolo-client-img:latest
    environment:
      PORT: 3000
      PROXY_API: http://yolo-web-backend:8080/
    ports:
      - 3000:3000
  yolo-web-backend:
    image: muriithike/yolo-client-img:latest
    environment:
      MONGODB_URI: mongodb://yolo-web-db:27017/yolomy    
    ports:
      - 8080:8080